[project]
name = "early-exits-testing"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "torch>=2.6.0",
  "torchvision>=0.21.0",
  "datasets>=2.14.0",
  "transformers>=4.36.0",
  "wandb>=0.15.0",
  "numpy>=1.26.0",
  "huggingface-cli",
  "sentencepiece",
]